train_args:
  num_epochs: 1
  learning_rate: 1.0e-5
  weight_decay: 0.01
  warmup_steps: 400
  checkpoint: null
  wandb: true
  wandb_project_name: "retriever"
  log_grads_every: 100
  log_lr_every: 10
  save_every: 4500 
  chunk_size: 32
  output_dir: "/shared/nas2/revanth3/query_free_rag/exp/sanity/no_prefix_gte_large/"
  # if using deepspeed, this will be ignored
  schedule_type: "linear"
  max_grad_norm: 1.0
  gradient_accumulation_steps: 2
  deepspeed: true
  deepspeed_config: "configs/deepspeed/ds_config.json"
  adam_beta1: 0.9
  adam_beta2: 0.999
  grad_cache: false
  loss_fn: "clip"
  use_fp8: false
  clamp_logits: false
  logit_max: 100

model_args:
  model_type: "encoder"
  logit_scale: 50
  trainable_logit_scale: false
  seq_len: 512
  pooling: "cls"
  nomic_encoder: false
  add_prefix: false
  use_fused_kernels: false
  num_negatives: 10 
  tokenizer_name: "Alibaba-NLP/gte-large-en-v1.5"
  model_name: "Alibaba-NLP/gte-large-en-v1.5"
  pretrained: true

data_args:
  input_shards: "configs/data/finetune_triplets.yaml"
  workers: 8 
<<<<<<< HEAD
  batch_size: 96
=======
  batch_size: 128
>>>>>>> 94d1a58 (Add separate query - document encoders)
  seed: 42
  shuffle: false
  download: true
  streaming: false
  weighted_sampling: false
  verbose: true
